// RootLayout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientOnlyReactQueryProvider from "./ClientOnlyReactQueryProvider"; // Import your client-side provider
import { Toaster } from "sonner";
import ThemeProvider from "@/components/layout/ThemeToggle/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientOnlyReactQueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Toaster />
            {children}
          </ThemeProvider>
        </ClientOnlyReactQueryProvider>
      </body>
    </html>
  );
}
